
spring:
  datasource:
    dynamic:
      primary: product
      strict: true
      datasource:
        product:
          url: jdbc:mysql://119.91.214.135:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: k1q235pr
          driver-class-name: com.mysql.cj.jdbc.Driver
        storage:
          url: jdbc:mysql://119.91.214.135:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: k1q235pr
          driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8002