server:
  port: 30002

spring:
  application:
    name: cases-mall
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: mall
      strict: true
      datasource:
        mall:
          url: jdbc:mysql://127.0.0.1:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver






# 配置 MyBatis-Plus SQL 日志打印器
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
