#spring:
#  security:
#    user:
#      name: yunze
#      password: 123456
#      roles: admin

logging:
  level:
    org.springframework: DEBUG


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://159.75.135.41:3306/blogcloud?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: blogcloud
    password: mXfTRksi2pYebHNy
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    prefix: /static
    suffix: .html
    cache: false